version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE : backendassessment
      MYSQL_USER : homestead
      MYSQL_PASSWORD : secret
      MYSQL_ROOT_PASSWORD : secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    image: php:7.4.33-zts-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    tty: true
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


